//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezerwacje
    {
        public int Id { get; set; }
        public Nullable<int> IdKsiazki { get; set; }
        public Nullable<int> IdCzytelnika { get; set; }
        public Nullable<System.DateTime> DataRezerwacji { get; set; }
        public Nullable<System.DateTime> DataOdbioruKsiazki { get; set; }
    
        public virtual Czytelnicy Czytelnicy { get; set; }
        public virtual Ksiazki Ksiazki { get; set; }
    }
}
