
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MVVMFirma.Models.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class RodzajCzlonkostwa
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public RodzajCzlonkostwa()
    {

        this.Czytelnicy = new HashSet<Czytelnicy>();

    }


    public int Id { get; set; }

    public string NazwaCzlonkowstwa { get; set; }

    public Nullable<int> MaxKsiazekWypozyczonych { get; set; }

    public Nullable<int> MaxCzasWypozyczenia { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Czytelnicy> Czytelnicy { get; set; }

}

}
